export const parts = ["Head", "Neck", "Rib", "Hand"];
export const bodyHeadings = [
  "The human head is an anatomical unit that consists of the skull, hyoid bone and cervical vertebrae.",
  "The neck is the part of the body on many vertebrates that connects the head with the torso and provides the mobility and movements of the head",
  "In vertebrate anatomy, ribs (Latin: costae) are the long curved bones which form the rib cage, part of the axial skeleton",
  "A hand is a prehensile, multi-fingered appendage located at the end of the forearm or forelimb of primates such as humans, chimpanzees, monkeys, and lemurs",
];

export const bodyDetails = [
  "A typical insect head is composed of eyes, antennae, and components of mouth.   As these components differ substantially from insect to insect, they form important identification links. Eyes in the head found,     in several types of insects, are in the form of a pair of compound eyes with multiple faces. In many other types of insects the compound eyes are seen in a single facet or group of single facets. In some cases, the eyes may be seen as marks on the dorsal or located near or toward the head, two or three ocelli (single faceted organs).",
  "The thyroid cartilage of the larynx forms a bulge in the midline of the neck called the Adam's apple. The Adam's apple is usually more prominent in men.[9][10] Inferior to the Adam's apple is the cricoid cartilage. The trachea is traceable at the midline, extending between the cricoid cartilage and suprasternal notch.     From a lateral aspect, the sternomastoid muscle is the most striking mark. It separates the anterior triangle of the neck from the posterior. The upper part of the anterior triangle contains the submandibular glands, which lie just below the posterior half of the mandible. The line of the common and the external carotid arteries can be marked by joining the sterno-clavicular articulation to the angle of the jaw. Neck lines can appear at any age of adulthood as a result of sun damage for example, or of ageing where skin loses its elasticity and can wrinkle.",
  "Human ribs are flat bones that form part of the rib cage to help protect internal organs. Humans usually have 24 ribs, in 12 pairs.[2] 1 in 500 people have an extra rib known as a cervical rib. All are attached at the back to the thoracic vertebrae and are numbered from 1–12 according to the vertebrae to which they attach.",
  "Many mammals and other animals have grasping appendages similar in form to a hand such as paws, claws, and talons, but these are not scientifically considered to be grasping hands. The scientific use of the term hand in this sense to distinguish the terminations of the front paws from the hind ones is an example of anthropomorphism. The only true grasping hands appear in the mammalian order of primates. Hands must also have opposable thumbs, as described later in the text.",
];
